
#ifndef __TTS_ERROR_CODE_H__
#define __TTS_ERROR_CODE_H__



#define TEC_NONE						0
#define TOK								0

#define TEC_BASIC_BASE					0X0001
#define TEC_UNKNOWN					    TEC_BASIC_BASE
#define TEC_INVALID_PARAM				(TEC_BASIC_BASE+1)
#define TEC_UNSUPPORTED				    (TEC_BASIC_BASE+2)
#define TEC_NO_MEMORY					(TEC_BASIC_BASE+3)
#define TEC_BAD_STATE					(TEC_BASIC_BASE+4)
#define TEC_USER_CANCEL				    (TEC_BASIC_BASE+5)
#define TEC_EXPIRED					    (TEC_BASIC_BASE+6)
#define TEC_USER_PAUSE					(TEC_BASIC_BASE+7)
#define TEC_BUFFER_OVERFLOW		        (TEC_BASIC_BASE+8)
#define TEC_BUFFER_UNDERFLOW		    (TEC_BASIC_BASE+9)
#define TEC_NO_DISKSPACE				(TEC_BASIC_BASE+10)



#define TEC_FILE_BASE					0X1000
#define TEC_FILE_GENERAL				TEC_FILE_BASE
#define TEC_FILE_NOT_EXIST				(TEC_FILE_BASE+1)
#define TEC_FILE_EXIST					(TEC_FILE_BASE+2)
#define TEC_FILE_EOF					(TEC_FILE_BASE+3)
#define TEC_FILE_FULL					(TEC_FILE_BASE+4)
#define TEC_FILE_SEEK					(TEC_FILE_BASE+5)
#define TEC_FILE_READ					(TEC_FILE_BASE+6)
#define TEC_FILE_WRITE					(TEC_FILE_BASE+7)
#define TEC_FILE_OPEN					(TEC_FILE_BASE+8)
#define TEC_FILE_DELETE				    (TEC_FILE_BASE+9)
#define TEC_FILE_RENAME				    (TEC_FILE_BASE+10)



#define TEC_KERNEL_BASE				    0X2000
#define TEC_KERNEL_GENERAL				TEC_KERNEL_BASE
#define TEC_THREAD_CREATE				(TEC_KERNEL_BASE+1)
#define TEC_THREAD_SET_PRIORITY		    (TEC_KERNEL_BASE+2)


#define TEC_NET_BASE					0X3000
#define TEC_NET_GENERAL				    TEC_NET_BASE
#define TEC_SOCKET_READ				    (TEC_NET_BASE+1)
#define TEC_SOCKET_WRITE				(TEC_NET_BASE+2)
#define TEC_SOCKET_CONNECT 			    (TEC_NET_BASE+3)
#define TEC_HTTP_GENERAL				(TEC_NET_BASE+4)
#define TEC_HTTP_DATA_NOT_READY		    (TEC_NET_BASE+5)
#define TEC_HTTP_EOF					(TEC_NET_BASE+6)
#define	TEC_HTTP_TIMEOUT				(TEC_NET_BASE+7)
#define	TEC_HTTP_REQUEST_FAIL			(TEC_NET_BASE+8)
#define	TEC_HTTP_NOBUFFERS				(TEC_NET_BASE+9)
#define	TEC_HTTP_RESPONSE_300			(TEC_HTTP_REQUEST_FAIL+300)
#define	TEC_HTTP_RESPONSE_301			(TEC_HTTP_REQUEST_FAIL+301)
#define	TEC_HTTP_RESPONSE_302			(TEC_HTTP_REQUEST_FAIL+302)
#define	TEC_HTTP_RESPONSE_303			(TEC_HTTP_REQUEST_FAIL+303)
#define	TEC_HTTP_RESPONSE_304			(TEC_HTTP_REQUEST_FAIL+304)
#define	TEC_HTTP_RESPONSE_305			(TEC_HTTP_REQUEST_FAIL+305)
#define	TEC_HTTP_RESPONSE_307			(TEC_HTTP_REQUEST_FAIL+307)
#define	TEC_HTTP_RESPONSE_400			(TEC_HTTP_REQUEST_FAIL+400)
#define	TEC_HTTP_RESPONSE_401			(TEC_HTTP_REQUEST_FAIL+401)
#define	TEC_HTTP_RESPONSE_402			(TEC_HTTP_REQUEST_FAIL+402)
#define	TEC_HTTP_RESPONSE_403			(TEC_HTTP_REQUEST_FAIL+403)
#define	TEC_HTTP_RESPONSE_404			(TEC_HTTP_REQUEST_FAIL+404)
#define	TEC_HTTP_RESPONSE_405			(TEC_HTTP_REQUEST_FAIL+405)
#define	TEC_HTTP_RESPONSE_406			(TEC_HTTP_REQUEST_FAIL+406)
#define	TEC_HTTP_RESPONSE_407			(TEC_HTTP_REQUEST_FAIL+407)
#define	TEC_HTTP_RESPONSE_408			(TEC_HTTP_REQUEST_FAIL+408)
#define	TEC_HTTP_RESPONSE_409			(TEC_HTTP_REQUEST_FAIL+409)
#define	TEC_HTTP_RESPONSE_410			(TEC_HTTP_REQUEST_FAIL+410)
#define	TEC_HTTP_RESPONSE_411			(TEC_HTTP_REQUEST_FAIL+411)
#define	TEC_HTTP_RESPONSE_412			(TEC_HTTP_REQUEST_FAIL+412)
#define	TEC_HTTP_RESPONSE_413			(TEC_HTTP_REQUEST_FAIL+413)
#define	TEC_HTTP_RESPONSE_414			(TEC_HTTP_REQUEST_FAIL+414)
#define	TEC_HTTP_RESPONSE_415			(TEC_HTTP_REQUEST_FAIL+415)
#define	TEC_HTTP_RESPONSE_417			(TEC_HTTP_REQUEST_FAIL+417)
#define	TEC_HTTP_RESPONSE_500			(TEC_HTTP_REQUEST_FAIL+500)
#define	TEC_HTTP_RESPONSE_501			(TEC_HTTP_REQUEST_FAIL+501)
#define	TEC_HTTP_RESPONSE_502			(TEC_HTTP_REQUEST_FAIL+502)
#define	TEC_HTTP_RESPONSE_503			(TEC_HTTP_REQUEST_FAIL+503)
#define	TEC_HTTP_RESPONSE_504			(TEC_HTTP_REQUEST_FAIL+504)
#define	TEC_HTTP_RESPONSE_505			(TEC_HTTP_REQUEST_FAIL+505)


#define TEC_DISPLAY_BASE				0X5000
#define TEC_DISPLAY_GENERAL			    TEC_DISPLAY_BASE
#define TEC_DISPLAY_ALREADY_INIT        (TEC_DISPLAY_BASE + 1)
#define TEC_DISPLAY_INIT_FAIL       	(TEC_DISPLAY_BASE + 2)
#define TEC_DISPLAY_UNINIT_FAIL     	(TEC_DISPLAY_BASE + 3)
#define TEC_DISPLAY_NOT_INIT        	(TEC_DISPLAY_BASE + 4)
#define TEC_DISPLAY_DEVICE_FAIL     	(TEC_DISPLAY_BASE + 5)
#define TEC_DISPLAY_DRAW_FAIL       	(TEC_DISPLAY_BASE + 6)
#define TEC_DISPLAY_SHOWOVERLAY_FAIL 	(TEC_DISPLAY_BASE + 7)


#endif //__TTS_ERROR_CODE_H__

